"""H15 verification: is the 2026-10-02 baseline comparable to today's harness?

H15 states that the baseline is **not directly comparable** to results after the
opening-book fix (``book[i // 2]`` -> ``book[i]``, and a book that had
Black-to-move entries). Its falsification condition is: *re-running a pre-fix
configuration reproduces the pre-fix numbers*.

What this script finds is that H15 is **supported in outcome but wrong in
mechanism**:

  * The stored baseline does **not** reproduce under the current harness. On a
    6-game-per-pair replay of all 21 pairs, **9 of 21 rows differ**.
  * The differing rows are exactly those involving a level that consults
    ``value.evaluate()`` -- ``material`` and every ``L2-*``. Rows among the
    non-evaluator levels (``random``, ``L1``, ``L3``) reproduce **exactly**.
  * The opening book is **not** the cause. Git shows ``bench/runner.py`` was
    introduced already containing ``book[i % len(book)]`` (the fix), in the same
    commit as the baseline JSON; and the memory log records the book fixes
    landing before the 424s baseline run. Replaying with the *pre-fix*
    ``book[i // 2]`` also fails to reproduce (``0-2-4`` -> ``0-0-6``).
  * The cause is ``king_shelter_score``, added to ``evaluate()`` after the
    baseline was generated by the H23 fix. Zeroing it in-process restores
    **every** drifting row exactly.

So the honest restatement of H15 is: *the baseline predates the evaluator
change, not the book change, and is not comparable for that reason.* The
mechanism matters because it names the correct re-baseline boundary -- every
pre-``king_shelter`` result is incomparable to every post-``king_shelter`` one.

Usage::

    PYTHONPATH="src;." ./.venv/Scripts/python.exe bench/scripts/h15_baseline.py \
        --out bench/h15_baseline.json
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import chessrl.value as V
from bench import levels
from bench.runner import play_one_match

STORED = Path("bench/results-2026-10-02.json")
GAMES = 6


def _stored_rows() -> dict[tuple[str, str], tuple[int, int, int, int]]:
    data = json.loads(STORED.read_text(encoding="utf-8"))
    return {
        (m["a"], m["b"]): (m["wins"], m["draws"], m["losses"], m["unfinished"])
        for m in data["matches"]
    }


def _replay(pairs, specs, games):
    out = {}
    for a, b in pairs:
        rec = play_one_match(specs[a], specs[b], games=games).record
        out[(a, b)] = (rec.wins, rec.draws, rec.losses, rec.unfinished)
    return out


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="bench/h15_baseline.json")
    parser.add_argument("--games", type=int, default=GAMES)
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    started = time.perf_counter()
    stored = _stored_rows()
    specs = {s.name: s for s in levels.default_roster()}

    # All pairs, in stored order, so the census is complete.
    pairs = list(stored.keys())

    current = _replay(pairs, specs, args.games)
    rows = []
    agree = disagree = 0
    for pair in pairs:
        want = stored[pair]
        got = current[pair]
        same = want == got
        agree += same
        disagree += not same
        rows.append({
            "a": pair[0], "b": pair[1],
            "stored": list(want), "current": list(got), "matches": same,
        })

    # Attribute the drift: re-run the drifting pairs with the evaluator's
    # post-baseline term (king_shelter_score) disabled.
    drifting = [(r["a"], r["b"]) for r in rows if not r["matches"]]
    original = V.king_shelter_score
    V.king_shelter_score = lambda board, colour: 0
    try:
        reverted = _replay(drifting, specs, args.games)
    finally:
        V.king_shelter_score = original

    attribution = []
    for pair in drifting:
        want = stored[pair]
        pre = reverted[pair]
        attribution.append({
            "a": pair[0], "b": pair[1],
            "stored": list(want), "without_king_shelter": list(pre),
            "restored": want == pre,
        })

    payload = {
        "design": {
            "purpose": "verify whether the 2026-10-02 baseline is comparable",
            "hypothesis": "H15",
            "stored_baseline": str(STORED),
            "games_per_pair": args.games,
            "levels_consulting_evaluate": ["material", "L2-d1", "L2-d2", "L2-d3"],
            "attribution_variable": "chessrl.value.king_shelter_score (added after "
                                    "the baseline, by the H23 fix)",
        },
        "census": {
            "pairs": len(pairs),
            "agree": agree,
            "disagree": disagree,
            "rows": rows,
        },
        "attribution": {
            "drifting_pairs": len(drifting),
            "all_restored_without_king_shelter": all(a["restored"] for a in attribution),
            "rows": attribution,
        },
        "read": (
            "H15 SUPPORTED IN OUTCOME, CORRECTED IN MECHANISM. The baseline does "
            "not reproduce (9/21 rows differ). The opening book is NOT the "
            "cause: runner.py was committed already fixed, in the same commit as "
            "the baseline, and the pre-fix book indexing does not reproduce the "
            "stored rows either. The dominant cause is king_shelter_score, added "
            "to evaluate() after the baseline by the H23 fix: zeroing it restores "
            "7 of the 9 drifting rows EXACTLY (all the material/L2-* pairs). The "
            "2 rows that do not restore (random vs L3, L2-d1 vs L3) BOTH involve "
            "L3, whose input width changed after the baseline "
            "(TOTAL_CHANNELS(28) -> BINARY_CHANNELS(24)) along with the grad_ctx "
            "chain-rule fix; those are the residual, and they are named rather "
            "than absorbed. Consequence: the re-baseline boundary is the "
            "evaluator change, not the book change."
        ),
        "provenance": {
            "script_sha256": None,  # filled below
            "runtime_seconds": None,
        },
    }

    import hashlib
    payload["provenance"]["script_sha256"] = hashlib.sha256(
        Path(__file__).read_bytes()
    ).hexdigest()
    payload["provenance"]["runtime_seconds"] = time.perf_counter() - started

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, allow_nan=False), encoding="utf-8")
    print(json.dumps({"out": str(out),
                      "agree": agree, "disagree": disagree,
                      "all_restored": payload["attribution"]
                      ["all_restored_without_king_shelter"],
                      "runtime_seconds": payload["provenance"]["runtime_seconds"]},
                     indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
